import { DAY, TODAY, dLabel } from '../lib/dates.js';
import { money2, num, pct, won, wonK } from '../lib/format.js';
import { byCreator } from '../model/db.js';
import { campaignStats, liveOf, partsOf, viralScore } from '../model/stats.js';
import { $, esc } from '../ui/dom.js';
import { copyText, downloadFile, toCsv } from '../ui/html.js';
import { toast } from '../ui/overlay.js';

/* ============================================================
   CAMPAIGN TAB — REPORT HAND-OFF
   The report itself is generated by the existing Vively Toolkit
   (성과 리포트 tab). This screen packages the campaign so the
   toolkit can ingest it with one CSV import — column names match
   its parser exactly: creator, platform, url, views, likes,
   comments, shares, saves, reach, countries, status.
   ============================================================ */
export const TOOLKIT_FIELDS = ['creator', 'platform', 'url', 'views', 'likes', 'comments', 'shares', 'saves', 'reach', 'countries', 'status'];

export function toolkitRows(cp) {
  return partsOf(cp.id).filter((p) => p.content).map((p) => {
    const cr = byCreator[p.creatorId], c = p.content;
    return [
      cr.handle, c.platform, c.url, c.views, c.likes, c.comments, c.shares, c.saves, c.reach,
      c.topCountries.join(' / '),
      p.stage === 'live' ? 'Posted' : p.stage === 'review' ? 'In review' : 'Waiting'
    ];
  });
}

export function executiveSummary(cp) {
  const s = campaignStats(cp);
  const live = liveOf(cp.id);
  const top = live.map((p) => ({ p, v: viralScore(p) })).sort((a, b) => b.v - a.v)[0];
  const tierCount = {};
  live.forEach((p) => { const t = byCreator[p.creatorId].tier; tierCount[t] = (tierCount[t] || 0) + 1; });
  const tierText = Object.entries(tierCount).sort((a, b) => b[1] - a[1]).map(([t, n]) => `${n} ${t}`).join(', ');

  return [
    `${cp.brand} — ${cp.name}. ${dLabel(cp.start)} to ${dLabel(cp.end)}, ${cp.market} market.`,
    ``,
    `We contacted ${s.contacted} creators and confirmed ${s.confirmed} against a target of ${cp.targetCreators} (${pct(s.confirmRate, 0)} of everyone contacted said yes). ${s.delivered} pieces of content went live — a ${pct(s.deliveryRate, 0)} delivery rate on confirmed creators.`,
    ``,
    `Those posts generated ${num(s.views)} views and ${num(s.reach)} in reach, with ${num(s.eng)} engagements at a ${pct(s.er)} engagement rate. ${s.paidViews ? `${pct(s.paidViews / s.views, 0)} of views came from paid boosting; the remaining ${pct(s.organicViews / s.views, 0)} were organic.` : 'All views were organic — no paid boosting was used.'}`,
    ``,
    `Total spend of ${wonK(s.spend)} works out to ${money2(s.cpm)} CPM, ${money2(s.cpv)} per view and ${money2(s.cpe)} per engagement — ${wonK(s.cpi)} per confirmed creator.`,
    ``,
    top ? `Best performing post: ${byCreator[top.p.creatorId].handle} with ${num(top.p.content.views)} views, ${top.v.toFixed(1)}× that creator's own baseline. ${s.viralCount > 1 ? `${s.viralCount} posts in total beat their baseline by 3× or more.` : ''}` : '',
    tierText ? `Creator mix: ${tierText}.` : '',
    ``,
    `Recommendation: ${s.viralCount ? 'boost the top performers with paid spend while they still have momentum, and re-book those creators first next round. ' : ''}${s.deliveryRate < 0.8 ? 'Delivery rate came in under 80% — tighten the confirmation step with a firmer posting date before shipping. ' : ''}${s.cpm < 3000 ? 'CPM is strong for this category; this creator mix is worth repeating.' : 'Consider shifting budget toward micro creators, where CPM was lowest.'}`
  ].filter((x) => x !== undefined).join('\n');
}

export function reportTab(mount, cp) {
  const s = campaignStats(cp);
  const rows = toolkitRows(cp);

  mount.innerHTML = `
    <div class="note" style="margin-bottom:18px;">
      The client-facing report is built in <strong>Vively Toolkit → 성과 리포트</strong>. Export the pack below, open the toolkit,
      hit <strong>CSV 불러오기</strong> and paste the campaign fields. Everything else — KPI tiles, top performers, proof screenshots,
      printable PDF and the standalone HTML report — is already handled there.
    </div>

    <div class="grid g-2-1">
      <div>
        <div class="card" style="margin-bottom:16px;">
          <div class="card-head"><h3>Executive summary</h3><div class="sp"></div>
            <button class="btn sm" id="rpRegen">Regenerate</button>
            <button class="btn primary sm" id="rpCopySum">Copy</button></div>
          <p class="card-sub">Written from this campaign's real numbers. Paste into the toolkit's 리포트 요약 box.</p>
          <textarea id="rpSum" style="min-height:27vh;font-size:13px;line-height:1.7"></textarea>
        </div>

        <div class="card">
          <div class="card-head"><h3>Content rows going into the report (${rows.length})</h3></div>
          <p class="card-sub">Column names match the toolkit's CSV parser exactly, so the import is one click.</p>
          <div class="tbl-wrap" style="max-height:26vh;overflow-y:auto"><table class="tbl">
            <thead><tr>${TOOLKIT_FIELDS.map((f, i) => `<th${i >= 3 && i <= 8 ? ' class="num"' : ''}>${f}</th>`).join('')}</tr></thead>
            <tbody>${rows.map((r) => `<tr>${r.map((c, i) => `<td${i >= 3 && i <= 8 ? ' class="num"' : ''}>${i === 2 ? `<a href="${c}" target="_blank" rel="noopener">link</a>` : esc(typeof c === 'number' ? num(c) : c)}</td>`).join('')}</tr>`).join('') || `<tr><td colspan="11"><div class="empty">No content yet.</div></td></tr>`}</tbody>
          </table></div>
        </div>
      </div>

      <div>
        <div class="card" style="margin-bottom:16px;">
          <div class="card-head"><h3>Campaign fields</h3><div class="sp"></div><button class="btn xs" id="rpCopyFields">Copy all</button></div>
          <p class="card-sub">Paste these into 캠페인 정보 in the toolkit.</p>
          <dl class="kv">
            <dt>클라이언트</dt><dd id="fClient">${esc(cp.brand)}</dd>
            <dt>캠페인명</dt><dd id="fCampaign">${esc(cp.name)}</dd>
            <dt>기간</dt><dd id="fDates">${cp.start} ~ ${cp.end}</dd>
            <dt>패키지</dt><dd id="fPackage">${s.delivered} creators / ${rows.length} contents</dd>
          </dl>
        </div>

        <div class="card" style="margin-bottom:16px;">
          <div class="card-head"><h3>Headline numbers</h3></div>
          <dl class="kv" style="margin-top:10px">
            <dt>Total views</dt><dd>${num(s.views)}</dd>
            <dt>Total reach</dt><dd>${num(s.reach)}</dd>
            <dt>Engagements</dt><dd>${num(s.eng)}</dd>
            <dt>Engagement rate</dt><dd>${pct(s.er)}</dd>
            <dt>Posts delivered</dt><dd>${s.delivered}</dd>
            <dt>Spend</dt><dd>${won(s.spend)}</dd>
            <dt>CPM / CPV / CPE</dt><dd>${money2(s.cpm)} / ${money2(s.cpv)} / ${money2(s.cpe)}</dd>
            <dt>Viral posts</dt><dd>${s.viralCount}</dd>
          </dl>
        </div>

        <div class="card">
          <div class="card-head"><h3>Export pack</h3></div>
          <p class="card-sub">Everything the toolkit needs.</p>
          <div style="display:flex;flex-direction:column;gap:8px;">
            <button class="btn primary" id="rpCsv">Report CSV (toolkit format)</button>
            <button class="btn" id="rpJson">Full campaign JSON</button>
            <button class="btn" id="rpProof">Proof checklist (missing data)</button>
          </div>
        </div>
      </div>
    </div>
  `;

  $('#rpSum').value = executiveSummary(cp);
  $('#rpRegen').addEventListener('click', () => { $('#rpSum').value = executiveSummary(cp); toast('Regenerated'); });
  $('#rpCopySum').addEventListener('click', () => copyText($('#rpSum').value, 'Summary'));
  $('#rpCopyFields').addEventListener('click', () => copyText(
    `클라이언트: ${cp.brand}\n캠페인명: ${cp.name}\n기간: ${cp.start} ~ ${cp.end}\n패키지: ${s.delivered} creators / ${rows.length} contents`, 'Campaign fields'));
  $('#rpCsv').addEventListener('click', () => downloadFile(toCsv(TOOLKIT_FIELDS, rows),
    `vively-${cp.brand.toLowerCase().replace(/\W+/g, '-')}-report.csv`, 'text/csv;charset=utf-8'));
  $('#rpJson').addEventListener('click', () => downloadFile(JSON.stringify({
    campaign: cp, stats: s, summary: $('#rpSum').value,
    participants: partsOf(cp.id).map((p) => ({ ...p, creator: byCreator[p.creatorId] }))
  }, null, 2), `vively-${cp.id}-campaign.json`, 'application/json'));
  $('#rpProof').addEventListener('click', () => {
    const missing = partsOf(cp.id).filter((p) => p.content).filter((p) =>
      !p.content.views || !p.content.reach || !p.content.saves).map((p) => byCreator[p.creatorId].handle);
    const late = partsOf(cp.id).filter((p) => p.stage === 'shipped' && p.shippedAt && (TODAY - new Date(p.shippedAt)) / DAY > 10).map((p) => byCreator[p.creatorId].handle);
    copyText([
      `${cp.brand} — report readiness`,
      ``,
      `Missing analytics screenshots (${missing.length}): ${missing.join(', ') || 'none'}`,
      `Shipped 10+ days ago with no content (${late.length}): ${late.join(', ') || 'none'}`,
      ``,
      `Ask these creators for day-7 / day-14 insight screenshots before finalising the report.`
    ].join('\n'), 'Checklist');
  });
}
